//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySql.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleItem
    {
        public int Id { get; set; }
    	
        public string Name { get; set; }
    	
        public string A { get; set; }
    	
        public string B { get; set; }
    	
        public string C { get; set; }
    	
        public Nullable<System.DateTime> Date { get; set; }
    	
    }
    	public static  class SampleItem_Table
        {
    	 public static string TableName="SampleItem";
    	 
     	public static string Id= "Id";
     	public static string Name= "Name";
     	public static string A= "A";
     	public static string B= "B";
     	public static string C= "C";
     	public static string Date= "Date";
      

        }
     
    
}
